var res = {
    ENEMY_BOSS_001_PNG : "res/boss_deathworm.png",
    ENEMY_BOSS_002_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_003_PNG : "res/boss_umisasori.png",
    ENEMY_BOSS_004_PNG : "res/boss_jorougumo.png",
    ENEMY_BOSS_005_PNG : "res/boss_nessi2.png",
    ENEMY_BOSS_006_PNG : "res/boss_ningen.png",
    ENEMY_BOSS_007_PNG : "res/boss_deathworm.png",
    ENEMY_BOSS_008_PNG : "res/e_bifrons.png",
    ENEMY_BOSS_009_PNG : "res/boss_eligor.png",
    ENEMY_BOSS_010_PNG : "res/boss_belith.png",
    ENEMY_BOSS_011_PNG : "res/boss_balam.png",
    ENEMY_BOSS_012_PNG : "res/boss_bafomet-re.png",
    ENEMY_BOSS_013_PNG : "res/boss_murmur.png",
    ENEMY_BOSS_014_PNG : "res/boss_deathworm.png",
    ENEMY_BOSS_015_PNG : "res/boss_behemoth.png",
    ENEMY_BOSS_016_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_017_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_018_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_019_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_020_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_021_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_022_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_023_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_024_PNG : "res/boss_yoroiuo01.png",
    ENEMY_BOSS_025_PNG : "res/boss_yoroiuo01.png",
    ENEMY_NORMAL_000_PNG : "res/hallucigenia.png",
    ENEMY_NORMAL_001_PNG : "res/e_halphas.png",
    ENEMY_NORMAL_002_PNG : "res/e_kelpee.png",
    ENEMY_NORMAL_003_PNG : "res/e_tokoyogami.png",
    ENEMY_NORMAL_004_PNG : "res/e_ant-queen.png",
    ENEMY_NORMAL_005_PNG : "res/e_cthuluh2011-child.png",
    ENEMY_NORMAL_006_PNG : "res/e_fishes01.png",
    ENEMY_NORMAL_007_PNG : "res/e_giganuron.png",
    ENEMY_NORMAL_008_PNG : "res/e_itsumade.png",
    ENEMY_NORMAL_009_PNG : "res/e_wizard01.png",
    ENEMY_NORMAL_010_PNG : "res/e_cady.png",
    ENEMY_NORMAL_011_PNG : "res/e_kairyu.png",
    ENEMY_NORMAL_012_PNG : "res/e_keronya-re01.png",
    ENEMY_NORMAL_013_PNG : "res/e_maken-re01.png",
    ENEMY_NORMAL_014_PNG : "res/e_peryton.png",
    ENEMY_NORMAL_015_PNG : "res/e_raijuu.png",
    ENEMY_NORMAL_016_PNG : "res/e_forneus.png",
    ENEMY_NORMAL_017_PNG : "res/e_ant01.png",
    ENEMY_NORMAL_018_PNG : "res/e_honey01.png",
    ENEMY_NORMAL_019_PNG : "res/e_peryton.png",
    ENEMY_NORMAL_020_PNG : "res/e_cockatris.png",
    ENEMY_NORMAL_021_PNG : "res/e_deep-one-re03.png",
    ENEMY_NORMAL_022_PNG : "res/e_red-devil.png",
    ENEMY_NORMAL_023_PNG : "res/e_uvall.png",
    ENEMY_NORMAL_024_PNG : "res/e_ose.png",
    ENEMY_NORMAL_025_PNG : "res/e_naberius.png",
    ENEMY_NORMAL_026_PNG : "res/e_glasya-labolas.png",
    ENEMY_NORMAL_027_PNG : "res/e_fleurety.png",
    ENEMY_NORMAL_028_PNG : "res/e_dantalion.png",
    ENEMY_NORMAL_029_PNG : "res/e_coronzon.png",
    ENEMY_NORMAL_030_PNG : "res/e_botis.png",
    MAP_PNG : "res/basetype2_1.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}